name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: clone resources type repo
      uses: actions/checkout@master
      with:
        repository: concourse/resource-types
        path: ./warehouse/resource-types
    - name: go build
      needs: clone resources type repo
      run: |
        cd warehouse/web
        yarn install
        yarn build
        cd ..
        go build -v
        ./dutyfree
    - name: go test
      needs: [go build,clone resources type repo]
      run: |
        cd warehouse
        go test -v
      env: 
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

