name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      env: 
        GH_TOKEN: ${{ secrets.GRAPHQL_TOKEN }}

    - name: clone resources type repo
      uses: actions/checkout@master
      with:
        repository: concourse/resource-types
        path: ./warehouse/resource-types
    - name: go build
      run: |
        cd warehouse/web
        yarn install
        yarn build
        cd ..
        go build -v -o public

    - name: go test
      run: |
        cd warehouse
        go test -v
      env:
        TOKEN: ${{ secrets.GRAPHQL_TOKEN }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: "brehan.ibrahim@gmail.com"

