name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      env: 
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: clone resources type repo
      uses: actions/checkout@master
      with:
        repository: concourse/resource-types
        path: ./warehouse/resource-types
    - name: go build
      run: |
        cd warehouse/web
        yarn install
        yarn build
        cd ..
        go build -v


    - name: go test
      run: |
        cd warehouse
        go test -v

